"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i^zl6tox_sqq&j_oa^o*a$v0zz&29d^*=7d01wc)pp!51)y9im'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'users.User'
LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

STATIC_ROOT = "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    # Основное
    "site_title": "MUSIC LOTTO",
    "site_header": "MUSIC LOTTO Панель управления",
    "site_brand": "MUSIC LOTTO Admin",
    "site_logo": "/MUSIC_LOTTO.png",  # Логотип
    "site_logo_classes": "img-responsive shadow-sm",  # Классы оформления логотипа
    "site_logo_width": "128px",  # Ширина логотипа
    "site_logo_height": "auto",  # Пропорциональная высота
    "welcome_sign": "Добро пожаловать в административный раздел MUSIC LOTTO",
    "copyright": "MUSIC LOTTO © 2025",

    # Верхнее меню
    "topmenu_links": [
        {"name": "На сайт", "url": "/", "icon": "fas fa-globe"},  # Переход на главную сайта
    ],

    # Боковая панель
    "show_sidebar": True,
    "navigation_expanded": True,
    "custom_links": {
        "my_app": [
            {"name": "Статистика", "url": "/admin/my_app/report/", "icon": "fas fa-chart-bar"},
        ]
    },

    # Подключение кастомного CSS для стилизации
    "custom_css": "admin/custom.css",
    "custom_js": None,

    # Настройки интерфейса
    "ui_tweaks": {
        "theme": "darkly",  # Темная тема
        "dark_mode": True,  # Включение темного режима
        "navbar": "navbar-dark",  # Темный верхний бар
        "sidebar": "sidebar-dark-custom",  # Темная боковая панель
        "accent": "accent-custom",  # Пользовательский акцент
        "navbar_fixed": True,  # Закрепленный верхний бар
        "sidebar_fixed": True,  # Закрепленная боковая панель
        "body_small_text": True,  # Более мелкий текст
        "footer_small_text": True,
        "layout_boxed": False,  # Отключенный боксированный режим
    },
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",  # Основная тема оформления
    "dark_mode": True,
    "dark_mode_theme": "cyborg",  # Тема для темного режима
    "body_small_text": True,
    "navbar": "navbar-dark bg-dark",  # Верхняя панель - черная
    "sidebar": "sidebar-dark-primary",  # Боковая панель - тёмная
    "brand_colour": "navbar-dark",  # Цвет бренда
    "navbar_fixed": True,  # Закрепленный верхний бар
    "sidebar_fixed": True,  # Закрепленная боковая панель
    "footer_fixed": False,  # Не закреплять футер
    "layout_boxed": False,  # Не использовать боксированную компоновку
    "footer_small_text": True,
    "accent": "accent-black",  # Черный акцент
    "button_classes": {
        "primary": "btn-custom-dark",  # Кастомный стиль кнопок
        "secondary": "btn-outline-light",  # Альтернативный стиль кнопок
    },
}
