# Generated by Django 5.1.5 on 2025-01-21 15:47

import lotto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicLotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('is_active', models.BooleanField(default=True)),
                ('playlist_files', models.FileField(blank=True, upload_to=lotto.models.upload_to)),
            ],
        ),
    ]
