# Generated by Django 5.1.5 on 2025-01-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0002_remove_musiclotto_playlist_files_playlistfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiclotto',
            name='name',
            field=models.CharField(default=1, help_text='Введите название музыкальной лотереи', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musiclotto',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
    ]
